---
- name: Get basic information from Cisco IOS routers
  hosts: ios_routers
  tasks:
    - name: Get facts from IOS routers
      cisco.ios.ios_facts:

    - name: Get IOS version
      debug:
        msg: "IOS version: {{ ansible_net_version }}"

    - name: Get router serial number
      debug:
        msg: "S/N: {{ ansible_net_serialnum }}"
